name: KinD Cluster Setup
on:
  push:
    branches:
      - master

jobs:
  setup-kind-cluster:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up KinD cluster
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind create cluster

      - name: Extract Cluster Info
        run: |
          kubectlversion=$(kubectl version)
          kindversion=$(kind version)
          pods=$(kubectl get pods -A)
          nodes=$(kind get nodes --name kind)
          echo "kubectl Version: $kubectlversion" > kind-cluster-info.txt
          echo "KinD Version: $kindversion" >> kind-cluster-info.txt
          echo "Pods: $pods" >> kind-cluster-info.txt
          echo "Nodes: $nodes" >> kind-cluster-info.txt
          echo "How long spin up (Time): $((${{steps.end_time_kind.outputs.end_kind}} - ${{steps.start_time_kind.outputs.start_kind}})) seconds"  >> kind-cluster-info.txt
        shell: bash
